package fr.insee.survey.datacollectionmanagement.metadata.util;

import lombok.Getter;

@Getter
public enum PeriodEnum {

    A00(PeriodicityEnum.A, "annuel"),
    X00(PeriodicityEnum.X, "pluriannuel"),
    X01(PeriodicityEnum.X, "pluriannuel"),
    X02(PeriodicityEnum.X, "pluriannuel"),
    X03(PeriodicityEnum.X, "pluriannuel"),
    X04(PeriodicityEnum.X, "pluriannuel"),
    X05(PeriodicityEnum.X, "pluriannuel"),
    X06(PeriodicityEnum.X, "pluriannuel"),
    X07(PeriodicityEnum.X, "pluriannuel"),
    X08(PeriodicityEnum.X, "pluriannuel"),
    X09(PeriodicityEnum.X, "pluriannuel"),
    X10(PeriodicityEnum.X, "pluriannuel"),
    X11(PeriodicityEnum.X, "pluriannuel"),
    X12(PeriodicityEnum.X, "pluriannuel"),
    X13(PeriodicityEnum.X, "pluriannuel"),
    X14(PeriodicityEnum.X, "pluriannuel"),
    X15(PeriodicityEnum.X, "pluriannuel"),
    X16(PeriodicityEnum.X, "pluriannuel"),
    X17(PeriodicityEnum.X, "pluriannuel"),
    X18(PeriodicityEnum.X, "pluriannuel"),
    X19(PeriodicityEnum.X, "pluriannuel"),
    X20(PeriodicityEnum.X, "pluriannuel"),
    X21(PeriodicityEnum.X, "pluriannuel"),
    X22(PeriodicityEnum.X, "pluriannuel"),
    X23(PeriodicityEnum.X, "pluriannuel"),
    X24(PeriodicityEnum.X, "pluriannuel"),
    X25(PeriodicityEnum.X, "pluriannuel"),
    X26(PeriodicityEnum.X, "pluriannuel"),
    X27(PeriodicityEnum.X, "pluriannuel"),
    X28(PeriodicityEnum.X, "pluriannuel"),
    X29(PeriodicityEnum.X, "pluriannuel"),
    X30(PeriodicityEnum.X, "pluriannuel"),
    X31(PeriodicityEnum.X, "pluriannuel"),
    X32(PeriodicityEnum.X, "pluriannuel"),
    X33(PeriodicityEnum.X, "pluriannuel"),
    X34(PeriodicityEnum.X, "pluriannuel"),
    X35(PeriodicityEnum.X, "pluriannuel"),
    X36(PeriodicityEnum.X, "pluriannuel"),
    X37(PeriodicityEnum.X, "pluriannuel"),
    X38(PeriodicityEnum.X, "pluriannuel"),
    X39(PeriodicityEnum.X, "pluriannuel"),
    X40(PeriodicityEnum.X, "pluriannuel"),
    X41(PeriodicityEnum.X, "pluriannuel"),
    X42(PeriodicityEnum.X, "pluriannuel"),
    X43(PeriodicityEnum.X, "pluriannuel"),
    X44(PeriodicityEnum.X, "pluriannuel"),
    X45(PeriodicityEnum.X, "pluriannuel"),
    X46(PeriodicityEnum.X, "pluriannuel"),
    X47(PeriodicityEnum.X, "pluriannuel"),
    X48(PeriodicityEnum.X, "pluriannuel"),
    X49(PeriodicityEnum.X, "pluriannuel"),
    X50(PeriodicityEnum.X, "pluriannuel"),
    X51(PeriodicityEnum.X, "pluriannuel"),
    X52(PeriodicityEnum.X, "pluriannuel"),
    X53(PeriodicityEnum.X, "pluriannuel"),
    X54(PeriodicityEnum.X, "pluriannuel"),
    X55(PeriodicityEnum.X, "pluriannuel"),
    X56(PeriodicityEnum.X, "pluriannuel"),
    X57(PeriodicityEnum.X, "pluriannuel"),
    X58(PeriodicityEnum.X, "pluriannuel"),
    X59(PeriodicityEnum.X, "pluriannuel"),
    X60(PeriodicityEnum.X, "pluriannuel"),
    X61(PeriodicityEnum.X, "pluriannuel"),
    X62(PeriodicityEnum.X, "pluriannuel"),
    X63(PeriodicityEnum.X, "pluriannuel"),
    X64(PeriodicityEnum.X, "pluriannuel"),
    X65(PeriodicityEnum.X, "pluriannuel"),
    X66(PeriodicityEnum.X, "pluriannuel"),
    X67(PeriodicityEnum.X, "pluriannuel"),
    X68(PeriodicityEnum.X, "pluriannuel"),
    X69(PeriodicityEnum.X, "pluriannuel"),
    X70(PeriodicityEnum.X, "pluriannuel"),
    X71(PeriodicityEnum.X, "pluriannuel"),
    X72(PeriodicityEnum.X, "pluriannuel"),
    X73(PeriodicityEnum.X, "pluriannuel"),
    X74(PeriodicityEnum.X, "pluriannuel"),
    X75(PeriodicityEnum.X, "pluriannuel"),
    X76(PeriodicityEnum.X, "pluriannuel"),
    X77(PeriodicityEnum.X, "pluriannuel"),
    X78(PeriodicityEnum.X, "pluriannuel"),
    X79(PeriodicityEnum.X, "pluriannuel"),
    X80(PeriodicityEnum.X, "pluriannuel"),
    X81(PeriodicityEnum.X, "pluriannuel"),
    X82(PeriodicityEnum.X, "pluriannuel"),
    X83(PeriodicityEnum.X, "pluriannuel"),
    X84(PeriodicityEnum.X, "pluriannuel"),
    X85(PeriodicityEnum.X, "pluriannuel"),
    X86(PeriodicityEnum.X, "pluriannuel"),
    X87(PeriodicityEnum.X, "pluriannuel"),
    X88(PeriodicityEnum.X, "pluriannuel"),
    X89(PeriodicityEnum.X, "pluriannuel"),
    X90(PeriodicityEnum.X, "pluriannuel"),
    X91(PeriodicityEnum.X, "pluriannuel"),
    X92(PeriodicityEnum.X, "pluriannuel"),
    X93(PeriodicityEnum.X, "pluriannuel"),
    X94(PeriodicityEnum.X, "pluriannuel"),
    X95(PeriodicityEnum.X, "pluriannuel"),
    X96(PeriodicityEnum.X, "pluriannuel"),
    X97(PeriodicityEnum.X, "pluriannuel"),
    X98(PeriodicityEnum.X, "pluriannuel"),
    X99(PeriodicityEnum.X, "pluriannuel"),
    S01(PeriodicityEnum.S, "1er semestre"),
    S02(PeriodicityEnum.S, "2nd semestre"),
    T01(PeriodicityEnum.T, "1er trimestre"),
    T02(PeriodicityEnum.T, "2e trimestre"),
    T03(PeriodicityEnum.T, "3e trimestre"),
    T04(PeriodicityEnum.T, "4e trimestre"),
    M01(PeriodicityEnum.M, "janvier"),
    M02(PeriodicityEnum.M, "février"),
    M03(PeriodicityEnum.M, "mars"),
    M04(PeriodicityEnum.M, "avril"),
    M05(PeriodicityEnum.M, "mai"),
    M06(PeriodicityEnum.M, "juin"),
    M07(PeriodicityEnum.M, "juillet"),
    M08(PeriodicityEnum.M, "août"),
    M09(PeriodicityEnum.M, "septembre"),
    M10(PeriodicityEnum.M, "octobre"),
    M11(PeriodicityEnum.M, "novembre"),
    M12(PeriodicityEnum.M, "décembre"),
    B01(PeriodicityEnum.B, "1er bimestre"),
    B02(PeriodicityEnum.B, "2e bimestre"),
    B03(PeriodicityEnum.B, "3e bimestre"),
    B04(PeriodicityEnum.B, "4e bimestre"),
    B05(PeriodicityEnum.B, "5e bimestre"),
    B06(PeriodicityEnum.B, "6e bimestre"),

    ;

    PeriodEnum(PeriodicityEnum period, String value) {
        this.value = value;
        this.period = period;
    }

    final PeriodicityEnum period;

    final String value;
    
    public static PeriodEnum fromValue(String v) {
        for (PeriodEnum c : PeriodEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
